globalThis.COLOR_CATEGORIES = {
  red: { label: "Red" },
  green: { label: "Green" },
  orange: { label: "Orange" },
  "yellow-white": { label: "Yellow / White" },
  "blue-purple": { label: "Blue / Purple" },
};

globalThis.PRODUCE_DATABASE = [
  { name: "Apple", type: "fruit", category: "red" },
  { name: "Banana", type: "fruit", category: "yellow-white" },
  { name: "Orange", type: "fruit", category: "orange" },
  { name: "Strawberry", type: "fruit", category: "red" },
  { name: "Blueberry", type: "fruit", category: "blue-purple" },
  { name: "Grape", type: "fruit", category: "blue-purple" },
  { name: "Lemon", type: "fruit", category: "yellow-white" },
  { name: "Lime", type: "fruit", category: "green" },
  { name: "Peach", type: "fruit", category: "orange" },
  { name: "Pear", type: "fruit", category: "green" },
  { name: "Cherry", type: "fruit", category: "red" },
  { name: "Mango", type: "fruit", category: "orange" },
  { name: "Pineapple", type: "fruit", category: "yellow-white" },
  { name: "Watermelon", type: "fruit", category: "red" },
  { name: "Avocado", type: "fruit", category: "green" },
  { name: "Kiwi", type: "fruit", category: "green" },
  { name: "Coconut", type: "fruit", category: "yellow-white" },
  { name: "Cranberry", type: "fruit", category: "red" },
  { name: "Raspberry", type: "fruit", category: "red" },
  { name: "Blackberry", type: "fruit", category: "blue-purple" },
  { name: "Plum", type: "fruit", category: "blue-purple" },
  { name: "Apricot", type: "fruit", category: "orange" },
  { name: "Nectarine", type: "fruit", category: "orange" },
  { name: "Grapefruit", type: "fruit", category: "yellow-white" },
  { name: "Cantaloupe", type: "fruit", category: "orange" },
  { name: "Honeydew", type: "fruit", category: "green" },
  { name: "Melon", type: "fruit", category: "orange" },
  { name: "Pomegranate", type: "fruit", category: "red" },
  { name: "Fig", type: "fruit", category: "blue-purple" },
  { name: "Date", type: "fruit", category: "yellow-white" },
  { name: "Olive", type: "fruit", category: "green" },
  { name: "Plantain", type: "fruit", category: "yellow-white" },
  { name: "Lychee", type: "fruit", category: "yellow-white" },
  { name: "Papaya", type: "fruit", category: "orange" },
  { name: "Passion Fruit", type: "fruit", category: "yellow-white" },
  { name: "Dragon Fruit", type: "fruit", category: "red" },
  { name: "Guava", type: "fruit", category: "red" },
  { name: "Persimmon", type: "fruit", category: "orange" },
  { name: "Quince", type: "fruit", category: "yellow-white" },
  { name: "Clementine", type: "fruit", category: "orange" },
  { name: "Tangerine", type: "fruit", category: "orange" },
  { name: "Mandarin", type: "fruit", category: "orange" },
  { name: "Blood Orange", type: "fruit", category: "red" },
  { name: "Star Fruit", type: "fruit", category: "yellow-white" },
  { name: "Jackfruit", type: "fruit", category: "yellow-white" },
  { name: "Durian", type: "fruit", category: "yellow-white" },
  { name: "Rambutan", type: "fruit", category: "red" },
  { name: "Mangosteen", type: "fruit", category: "orange" },
  { name: "Longan", type: "fruit", category: "yellow-white" },
  { name: "Kumquat", type: "fruit", category: "orange" },
  { name: "Loquat", type: "fruit", category: "orange" },
  { name: "Tamarind", type: "fruit", category: "yellow-white" },
  { name: "Prune", type: "fruit", category: "blue-purple" },
  { name: "Raisin", type: "fruit", category: "blue-purple" },
  { name: "Currant", type: "fruit", category: "blue-purple" },
  { name: "Elderberry", type: "fruit", category: "blue-purple" },
  { name: "Boysenberry", type: "fruit", category: "blue-purple" },
  { name: "Mulberry", type: "fruit", category: "blue-purple" },
  { name: "Acai", type: "fruit", category: "blue-purple" },
  { name: "Goji Berry", type: "fruit", category: "red" },
  { name: "Dried Apricot", type: "fruit", category: "orange" },
  { name: "Dried Cranberry", type: "fruit", category: "red" },
  { name: "Dried Mango", type: "fruit", category: "orange" },
  { name: "Pluot", type: "fruit", category: "red" },
  { name: "Plumcot", type: "fruit", category: "blue-purple" },
  { name: "Cherimoya", type: "fruit", category: "green" },
  { name: "Feijoa", type: "fruit", category: "green" },
  { name: "Soursop", type: "fruit", category: "green" },
  { name: "Breadfruit", type: "fruit", category: "green" },
  { name: "Pitaya", type: "fruit", category: "red" },
  { name: "Key Lime", type: "fruit", category: "green" },
  { name: "Meyer Lemon", type: "fruit", category: "yellow-white" },
  { name: "Pomelo", type: "fruit", category: "green" },
  { name: "Tangelo", type: "fruit", category: "orange" },
  { name: "Satsuma", type: "fruit", category: "yellow-white" },
  { name: "Mamey Sapote", type: "fruit", category: "orange" },
  { name: "Sapodilla", type: "fruit", category: "green" },
  { name: "Tamarillo", type: "fruit", category: "red" },
  { name: "Jujube", type: "fruit", category: "red" },
  { name: "Black Currant", type: "fruit", category: "blue-purple" },
  { name: "Black Raspberry", type: "fruit", category: "red" },
  { name: "Yuca", type: "vegetable", category: "yellow-white" },
  { name: "Finger Lime", type: "fruit", category: "green" },
  { name: "Pawpaw", type: "fruit", category: "yellow-white" },
  { name: "Sugar Apple", type: "fruit", category: "green" },
  { name: "Jabuticaba", type: "fruit", category: "blue-purple" },
  { name: "Santol", type: "fruit", category: "yellow-white" },
  { name: "Snake Fruit", type: "fruit", category: "red" },
  { name: "Salak", type: "fruit", category: "red" },
  { name: "Crenshaw Melon", type: "fruit", category: "orange" },
  { name: "Nashi Pear", type: "fruit", category: "yellow-white" },
  { name: "Strawberry Guava", type: "fruit", category: "red" },
  { name: "Golden Raspberry", type: "fruit", category: "red" },
  { name: "Gooseberry", type: "fruit", category: "green" },
  { name: "Marionberry", type: "fruit", category: "yellow-white" },
  { name: "Huckleberry", type: "fruit", category: "blue-purple" },
  { name: "Lingonberry", type: "fruit", category: "red" },
  { name: "Prickly Pear", type: "fruit", category: "red" },
  { name: "Crabapple", type: "fruit", category: "red" },
  { name: "Noni", type: "fruit", category: "green" },
  { name: "Tomato", type: "vegetable", category: "red" },
  { name: "Potato", type: "vegetable", category: "yellow-white" },
  { name: "Onion", type: "vegetable", category: "yellow-white" },
  { name: "Carrot", type: "vegetable", category: "orange" },
  { name: "Lettuce", type: "vegetable", category: "green" },
  { name: "Spinach", type: "vegetable", category: "green" },
  { name: "Broccoli", type: "vegetable", category: "green" },
  { name: "Cauliflower", type: "vegetable", category: "yellow-white" },
  { name: "Celery", type: "vegetable", category: "green" },
  { name: "Cucumber", type: "vegetable", category: "green" },
  { name: "Bell Pepper", type: "vegetable", category: "green" },
  { name: "Corn", type: "vegetable", category: "yellow-white" },
  { name: "Garlic", type: "vegetable", category: "yellow-white" },
  { name: "Mushroom", type: "vegetable", category: "yellow-white" },
  { name: "Zucchini", type: "vegetable", category: "green" },
  { name: "Squash", type: "vegetable", category: "orange" },
  { name: "Pumpkin", type: "vegetable", category: "orange" },
  { name: "Sweet Potato", type: "vegetable", category: "yellow-white" },
  { name: "Kale", type: "vegetable", category: "green" },
  { name: "Cabbage", type: "vegetable", category: "green" },
  { name: "Asparagus", type: "vegetable", category: "green" },
  { name: "Green Beans", type: "vegetable", category: "green" },
  { name: "Peas", type: "vegetable", category: "green" },
  { name: "Eggplant", type: "vegetable", category: "blue-purple" },
  { name: "Radish", type: "vegetable", category: "red" },
  { name: "Beet", type: "vegetable", category: "red" },
  { name: "Turnip", type: "vegetable", category: "yellow-white" },
  { name: "Jalapeño", type: "vegetable", category: "yellow-white" },
  { name: "Ginger", type: "vegetable", category: "yellow-white" },
  { name: "Scallion", type: "vegetable", category: "green" },
  { name: "Shallot", type: "vegetable", category: "yellow-white" },
  { name: "Leek", type: "vegetable", category: "green" },
  { name: "Artichoke", type: "vegetable", category: "green" },
  { name: "Arugula", type: "vegetable", category: "green" },
  { name: "Bok Choy", type: "vegetable", category: "green" },
  { name: "Brussels Sprouts", type: "vegetable", category: "green" },
  { name: "Butternut Squash", type: "vegetable", category: "orange" },
  { name: "Chard", type: "vegetable", category: "green" },
  { name: "Cilantro", type: "vegetable", category: "green" },
  { name: "Parsley", type: "vegetable", category: "green" },
  { name: "Basil", type: "vegetable", category: "green" },
  { name: "Mint", type: "vegetable", category: "green" },
  { name: "Dill", type: "vegetable", category: "green" },
  { name: "Chives", type: "vegetable", category: "green" },
  { name: "Collard Greens", type: "vegetable", category: "green" },
  { name: "Edamame", type: "vegetable", category: "green" },
  { name: "Fennel", type: "vegetable", category: "green" },
  { name: "Horseradish", type: "vegetable", category: "green" },
  { name: "Jicama", type: "vegetable", category: "yellow-white" },
  { name: "Kohlrabi", type: "vegetable", category: "green" },
  { name: "Mustard Greens", type: "vegetable", category: "green" },
  { name: "Okra", type: "vegetable", category: "green" },
  { name: "Oregano", type: "vegetable", category: "green" },
  { name: "Parsnip", type: "vegetable", category: "yellow-white" },
  { name: "Rhubarb", type: "vegetable", category: "red" },
  { name: "Rosemary", type: "vegetable", category: "green" },
  { name: "Rutabaga", type: "vegetable", category: "yellow-white" },
  { name: "Sage", type: "vegetable", category: "green" },
  { name: "Thyme", type: "vegetable", category: "green" },
  { name: "Tomatillo", type: "vegetable", category: "yellow-white" },
  { name: "Water Chestnut", type: "vegetable", category: "yellow-white" },
  { name: "Watercress", type: "vegetable", category: "green" },
  { name: "Yam", type: "vegetable", category: "orange" },
  { name: "Acorn Squash", type: "vegetable", category: "yellow-white" },
  { name: "Broccolini", type: "vegetable", category: "green" },
  { name: "Chayote", type: "vegetable", category: "green" },
  { name: "Chili Pepper", type: "vegetable", category: "red" },
  { name: "Chinese Broccoli", type: "vegetable", category: "green" },
  { name: "Daikon", type: "vegetable", category: "yellow-white" },
  { name: "Endive", type: "vegetable", category: "green" },
  { name: "Habanero", type: "vegetable", category: "orange" },
  { name: "Hearts of Palm", type: "vegetable", category: "yellow-white" },
  { name: "Kabocha Squash", type: "vegetable", category: "orange" },
  { name: "Lemongrass", type: "vegetable", category: "green" },
  { name: "Microgreens", type: "vegetable", category: "green" },
  { name: "Napa Cabbage", type: "vegetable", category: "green" },
  { name: "Nopales", type: "vegetable", category: "green" },
  { name: "Poblano Pepper", type: "vegetable", category: "yellow-white" },
  { name: "Radicchio", type: "vegetable", category: "green" },
  { name: "Romanesco", type: "vegetable", category: "green" },
  { name: "Serrano Pepper", type: "vegetable", category: "yellow-white" },
  { name: "Snow Peas", type: "vegetable", category: "green" },
  { name: "Sugar Snap Peas", type: "vegetable", category: "green" },
  { name: "Spaghetti Squash", type: "vegetable", category: "orange" },
  { name: "Yellow Squash", type: "vegetable", category: "yellow-white" },
  { name: "Cayenne Pepper", type: "vegetable", category: "red" },
  { name: "Chinese Cabbage", type: "vegetable", category: "green" },
  { name: "Dandelion Greens", type: "vegetable", category: "green" },
  { name: "Fava Bean", type: "vegetable", category: "green" },
  { name: "Garlic Scapes", type: "vegetable", category: "yellow-white" },
  { name: "Lima Bean", type: "vegetable", category: "green" },
  { name: "Mung Bean Sprouts", type: "vegetable", category: "green" },
  { name: "Oyster Mushroom", type: "vegetable", category: "yellow-white" },
  { name: "Portobello Mushroom", type: "vegetable", category: "yellow-white" },
  { name: "Shiitake Mushroom", type: "vegetable", category: "yellow-white" },
  { name: "Spring Mix", type: "vegetable", category: "green" },
  { name: "Turnip Greens", type: "vegetable", category: "green" },
  { name: "Ube", type: "vegetable", category: "blue-purple" },
  { name: "Water Spinach", type: "vegetable", category: "green" },
  { name: "Broccoli Rabe", type: "vegetable", category: "green" },
];
